logging:
  json_format: false
  level: trace

api:
  enabled: true
  port: 8080

api_keys:
  - key: admin

workers:
  enabled: true
  count: 1
  data_directory: ./data/worker

blob_store:
  type: memory

data_sink:
  type: memory

queue:
  type: memory

cache:
  type: memory

database:
  type: memory

destinations:
  - type: duckdb
    name: Local DuckDB file
    api_keys:
      - local
    settings:
      file: "./data/data.duckdb"

vault:
  type: memory